runtime: python37

instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  max_concurrent_requests: 80
  max_pending_latency: 2000ms

includes:
- secrets.yaml

handlers:
- url: /www/
  static_files: frontend/index.html
  upload: frontend/index.html

- url: /www/(.*\.(js|tag))$
  static_files: frontend/\1
  upload: frontend/.*\.(js|tag)$

- url: /.*
  script: auto 

